### ISSUE TITLE
Update Anthropic Client 

### ISSUE THREAD

**Issue by ghost** [hfvienna/jobzilla#1]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/hfvienna/jobzilla/blob/a73d4974bb3d00c93c8992dec75c368805d23c74/src/llm_claude.py#L26

--- 
Would love to know if this might help - https://github.com/BerriAI/litellm

~Simple I/O library, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by ghost** [comment]
cc: @hfvienna

**Comment by hfvienna** [comment]
@krrishdholakia Just commented it out and the code did not work anymore.
